// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OperacaoConteiner.Data;

namespace OperacaoConteiner.Migrations
{
    [DbContext(typeof(BancoContext))]
    partial class BancoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("OperacaoConteiner.Models.ContainerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("categoriaContainer")
                        .HasColumnType("int");

                    b.Property<string>("nomeCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroContainer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("statusContainer")
                        .HasColumnType("int");

                    b.Property<int>("tipoContainer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Container");
                });

            modelBuilder.Entity("OperacaoConteiner.Models.MovimentacaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdContainer")
                        .HasColumnType("int");

                    b.Property<int>("tipoMovimentação")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdContainer");

                    b.ToTable("Movimentacao");
                });

            modelBuilder.Entity("OperacaoConteiner.Models.MovimentacaoModel", b =>
                {
                    b.HasOne("OperacaoConteiner.Models.ContainerModel", "container")
                        .WithMany()
                        .HasForeignKey("IdContainer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("container");
                });
#pragma warning restore 612, 618
        }
    }
}
